# Generated by Django 5.0.3 on 2024-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0006_cloudphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePhotoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField()),
                ('images_list_url', models.TextField()),
                ('image_with_frame', models.TextField()),
                ('count_view', models.IntegerField(default=0)),
                ('tracking_code', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
